import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  const resume = await prisma.resume.findUnique({ where: { id } });
  if (!resume) {
    return NextResponse.json(
      { success: false, message: "Resume not found" },
      { status: 404 }
    );
  }

  const matchedCount = resume.keywords
    ? resume.keywords.split(", ").filter(Boolean).length
    : 0;
  const missingCount = resume.missingKeywords
    ? resume.missingKeywords.split(", ").filter(Boolean).length
    : 0;
  const totalKeywords = matchedCount + missingCount;

  const rating =
    resume.atsScore != null && resume.atsScore >= 90
      ? "Excellent"
      : resume.atsScore != null && resume.atsScore >= 70
        ? "Good"
        : "Needs Improvement";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ATS Report - ${resume.fileName}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 28px; margin-bottom: 8px; border-bottom: 2px solid #eee; padding-bottom: 4px; }
    .score { font-size: 48px; font-weight: bold; margin: 16px 0; }
    .rating { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 14px; font-weight: 600; }
    .rating-excellent { background: #dcfce7; color: #166534; }
    .rating-good { background: #fef9c3; color: #854d0e; }
    .rating-needs { background: #fee2e2; color: #991b1b; }
    .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 13px; margin: 2px 4px 2px 0; }
    .matched { background: #dcfce7; color: #166534; }
    .missing { background: #fee2e2; color: #991b1b; }
    .section { margin: 16px 0; }
    ul { padding-left: 20px; }
    li { margin: 4px 0; color: #333; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>ATS Resume Report</h1>
  <p class="meta">
    ${resume.fileName} &middot; ${resume.jobRole || "N/A"} &middot;
    Analyzed ${new Date(resume.createdAt).toLocaleDateString()}
    &middot; Source: ${resume.keywordSource === "jd" ? "Job Description" : "Role Library"}
  </p>

  <div class="score">${resume.atsScore ?? 0}/100</div>
  <div class="rating rating-${rating === "Excellent" ? "excellent" : rating === "Good" ? "good" : "needs"}">${rating}</div>

  <h2>Keyword Match</h2>
  <p>${matchedCount} of ${totalKeywords} keywords matched</p>

  <div class="section">
    <strong>Keywords Found</strong>
    <div>${(resume.keywords ? resume.keywords.split(", ").filter(Boolean) : []).map((k: string) => `<span class="badge matched">${k}</span>`).join(" ") || "None"}</div>
  </div>

  <div class="section">
    <strong>Missing Keywords</strong>
    <div>${(resume.missingKeywords ? resume.missingKeywords.split(", ").filter(Boolean) : []).map((k: string) => `<span class="badge missing">${k}</span>`).join(" ") || "None"}</div>
  </div>

  <h2>Improvement Suggestions</h2>
  <ul>
    ${resume.suggestions ? resume.suggestions.split(". ").filter(Boolean).map((s: string) => `<li>${s.replace(/\.$/, "")}</li>`).join("\n    ") : "<li>No suggestions needed</li>"}
  </ul>

  ${resume.jdKeywords ? `<h2>Job Description Keywords</h2><p>${resume.jdKeywords}</p>` : ""}

  ${resume.aiMissingSkills || resume.aiSuggestions || resume.aiSummary || resume.aiInterviewQuestions ? `<h2>AI Analysis</h2>` : ""}

  ${resume.aiMissingSkills ? `
  <h3>Missing Skills</h3>
  <p>${resume.aiMissingSkills}</p>` : ""}

  ${resume.aiSuggestions ? `
  <h3>Improvement Suggestions</h3>
  <ul>
    ${resume.aiSuggestions.split("\n").filter(Boolean).map((s: string) => `<li>${s}</li>`).join("\n    ")}
  </ul>` : ""}

  ${resume.aiSummary ? `
  <h3>Optimized Summary</h3>
  <p style="font-style:italic">${resume.aiSummary}</p>` : ""}

  ${resume.aiInterviewQuestions ? `
  <h3>Interview Questions</h3>
  <ul>
    ${resume.aiInterviewQuestions.split("\n").filter(Boolean).map((q: string) => `<li>${q}</li>`).join("\n    ")}
  </ul>` : ""}

  <footer>Generated by ATS Resume Optimizer</footer>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="ATS-Report-${resume.fileName.replace(/\.pdf$/i, "")}.html"`,
    },
  });
}
