import { NextResponse } from "next/server";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { pdf, Document as PdfDocument, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 11, color: "#1a1a1a" },
  title: { fontSize: 22, fontWeight: "bold", marginBottom: 12, color: "#1a1a1a" },
  heading: { fontSize: 14, fontWeight: "bold", marginTop: 14, marginBottom: 6, color: "#6366f1", borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingBottom: 4 },
  section: { marginBottom: 10 },
  text: { fontSize: 11, lineHeight: 1.5, marginBottom: 4 },
  bullet: { fontSize: 11, lineHeight: 1.5, marginBottom: 3, paddingLeft: 12 },
  skillRow: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginBottom: 8 },
  skillBadge: { fontSize: 9, padding: "3 8", borderRadius: 999, backgroundColor: "#f0f0ff", color: "#6366f1" },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#999", borderTopWidth: 1, borderTopColor: "#e5e7eb", paddingTop: 8, textAlign: "center" },
});

function generateDocx(summary: string, bullets: string[], skills: string[], fullContent: string) {
  return new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          text: "ATS Optimized Resume",
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: "Professional Summary",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 100 },
        }),
        new Paragraph({
          children: [new TextRun({ text: summary, size: 22 })],
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: "Skills",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 100 },
        }),
        new Paragraph({
          children: [new TextRun({ text: skills.join(", "), size: 22 })],
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: "Experience",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 100 },
        }),
        ...bullets.map(b => new Paragraph({
          children: [new TextRun({ text: `  \u2022  ${b}`, size: 22 })],
          spacing: { after: 80 },
        })),
        new Paragraph({
          text: "Full Resume",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 100 },
        }),
        ...fullContent.split("\n").filter(Boolean).map(line => {
          const trimmed = line.trim();
          if (trimmed.match(/^[A-Z][a-z]+(?: [A-Z][a-z]+)*:/) || trimmed === trimmed.toUpperCase() && trimmed.length > 2) {
            return new Paragraph({
              children: [new TextRun({ text: trimmed, bold: true, size: 22 })],
              spacing: { before: 200, after: 80 },
            });
          }
          return new Paragraph({
            children: [new TextRun({ text: trimmed, size: 22 })],
            spacing: { after: 60 },
          });
        }),
        new Paragraph({ spacing: { before: 400 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Generated by ATS Resume Optimizer", size: 18, color: "999999" })] }),
      ],
    }],
  });
}

function generatePdf(summary: string, bullets: string[], skills: string[], fullContent: string) {
  return pdf(
    <PdfDocument>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>ATS Optimized Resume</Text>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Professional Summary</Text>
          <Text style={pdfStyles.text}>{summary}</Text>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Skills</Text>
          <View style={pdfStyles.skillRow}>
            {skills.map((s, i) => (
              <Text key={i} style={pdfStyles.skillBadge}>{s}</Text>
            ))}
          </View>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Experience</Text>
          {bullets.map((b, i) => (
            <Text key={i} style={pdfStyles.bullet}>- {b}</Text>
          ))}
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Full Resume</Text>
          {fullContent.split("\n").filter(Boolean).map((line, i) => (
            <Text key={i} style={pdfStyles.text}>{line}</Text>
          ))}
        </View>

        <Text style={pdfStyles.footer}>Generated by ATS Resume Optimizer</Text>
      </Page>
    </PdfDocument>
  );
}

export async function POST(request: Request) {
  try {
    const { format, fileName, summary, bullets, skills, fullContent } = await request.json();

    if (!summary || !fullContent) {
      return NextResponse.json({ success: false, message: "Missing rewrite data" }, { status: 400 });
    }

    const safeName = (fileName || "resume").replace(/\.pdf$/i, "");

    if (format === "docx") {
      const doc = generateDocx(summary, bullets || [], skills || [], fullContent);
      const buffer = await Packer.toBuffer(doc);
      return new NextResponse(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${safeName}-Optimized.docx"`,
        },
      });
    }

    if (format === "pdf") {
      const instance = generatePdf(summary, bullets || [], skills || [], fullContent);
      const blob = await instance.toBlob();
      const arrayBuffer = await blob.arrayBuffer();
      return new NextResponse(new Uint8Array(arrayBuffer), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${safeName}-Optimized.pdf"`,
        },
      });
    }

    return NextResponse.json({ success: false, message: "Unsupported format" }, { status: 400 });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json({ success: false, message }, { status: 500 });
  }
}
